### ISSUE TITLE
post links are not using baseurl

### ISSUE THREAD

**Issue by s00ner** [riggraz/no-style-please#1]
I'm deploying a site to `https://example.com/my-site` and links to my posts are showing up as `https://example.com/blog-post.html` instead of `https://example.com/my-site/blog-post.html`

My _config.yml contains:
```
url: "https://example.com/my-site"
baseurl: "/my-site"
```
Is my config wrong or is this theme not working correctly?

**Comment by s00ner** [comment]
Minor addition. I tried switching only the theme in _config.yml and nothing else (I used minima) and the post links generated correctly so this issue seems to be unique to this theme.

**Comment by riggraz** [comment]
Hello s00ner!

Sorry for the late response, however the problem should now be fixed!
