### ISSUE TITLE
Custom url path?

### ISSUE THREAD

**Issue by nitanmarcel** [riggraz/no-style-please#13]
Is there a way to set a custom url for specific files?

What I want to do is to have a resume there but in two versions:  English version and my native language.

So the path would be:

example.com/resume/en
example.com/resume/ro

**Comment by jamiehowarth0** [comment]
Jekyll has an i18n plugin you can use, or you can create two pages with the following frontmatter:

```
---
permalink: /resume/en
---
```

and

```
---
permalink: /resume/ro
---
```

**Comment by nitanmarcel** [comment]
> Jekyll has an i18n plugin you can use, or you can create two pages with the following frontmatter:
> 
> ```
> ---
> permalink: /resume/en
> ---
> ```
> 
> and
> 
> ```
> ---
> permalink: /resume/ro
> ---
> ```

Awesome! Thanks for your work
