### ISSUE TITLE
width: 100% seems to cause ugly table

### ISSUE THREAD

**Issue by thinbold** [riggraz/no-style-please#19]
[These two lines](https://github.com/riggraz/no-style-please/blob/master/_sass/no-style-please.scss#L62-L63) in the CSS
```
table, th, td {
  width: 100%;
```

seems to cause tables to have a very wide column1, which looks like
```
|-------------------- entire  page --------------------|
|----------------- column1 -----------------|-- col2 --|
```

I would like to recommend to leave out L63, i.e., to delete `width: 100%;`.
The default behavior seems acceptable, and seems to be how other themes handle tables.

**Comment by riggraz** [comment]
Thanks for opening the issue! I decided to apply `width: 100%` only to the table element. See pull request #20 for the fix and let me know

**Comment by thinbold** [comment]
Thanks. Looks perfect to me.
