### ISSUE TITLE
Post example .md please?

### ISSUE THREAD

**Issue by ezaron** [riggraz/no-style-please#2]
Hi,
I am a complete Jekyll newbie, but I am attempting to use your theme. Would you be willing to post the markdown file, index.md, that you use for your blog? For some reason when I create an index file, none of the markdown I enter is rendered, and I assume I am making some novice mistake.
Thx for posting your nice theme.
-Ed

**Comment by riggraz** [comment]
You should leave the `index.md` file as is:
```
---
layout: home
---
```

Then you should customize how the index page looks by editing `_data/menu.yml` file, following [these instructions](https://github.com/riggraz/no-style-please#customize-the-menu). For example, [this](https://github.com/riggraz/no-style-please/blob/master/_data/menu.yml) is the default menu.yml file and [this](https://github.com/riggraz/riggraz.github.io/blob/master/_data/menu.yml) is the one I use for my personal blog.

If you want to write content (e.g. articles) you have to create posts or pages. The index.md file is meant to be the home page of your blog.

**Comment by ezaron** [comment]
aha! thx.
