### ISSUE TITLE
Date is not accurate

### ISSUE THREAD

**Issue by minseongkimdev** [riggraz/no-style-please#23]
Thanks for make great theme.

but i found some bug which is Date is not accurate. (in screenshot)

Do you kwow how to custom a date?

i appreciate your theme again. thanks.

![스크린샷 2021-05-13 오후 4 56 30](https://user-images.githubusercontent.com/44136364/118096325-2cd9a380-b40c-11eb-98d8-ee6a2088cff5.png)

**Comment by EchedeyLR** [comment]
I reply you from my user experience in this theme.

The date is using the format YYYY-mm-dd.

By default must be the format in the file-name (with a '-' before the title of the post) and in the header (the header requires an extended version which I generate using `date +"%Y-%m-%d %H:%M:%S %z"`).

This cannot be changed AFAIK but you can change the way it is viewed in the from page or in each post. I mean, only the low-level version (how you write and publish a post) is the thing that cannot be changed.

Here i show you an example in my `_config.yml` about how to change the format showed:

```
theme_config:
	  appearance: "auto"
	  back_home_text: "Atrás"
	  date_format: "%d-%m-%Y"
	permalink: /:categories/:year/:month/:day/:title:output_ext
```

**Comment by tanvincible** [comment]
Thanks @EchedelleLR for the comment. I am closing this issue.
