### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by seraphkz** [riggraz/no-style-please#25]
Hello, for some reason my blog is not formatted correctly in terms of font. And it's not in the center as well.
https://pedantic-hopper-b0aada.netlify.app/

**Comment by riggraz** [comment]
Hi seraphkz, the link you provided returns a not found.

**Comment by tanvincible** [comment]
I am closing this now as the link returns a not found error. Feel free to open it again (and change the label as well) if you think this is a mistake.
