### ISSUE TITLE
[Question] Why no-css?

### ISSUE THREAD

**Issue by victorbnl** [riggraz/no-style-please#26]
I just wanted to know what is the goal of using no-CSS? Is it related to performance or anything?

**Comment by riggraz** [comment]
Hi victorbnl! I wanted to create a minimal theme using the bare minimum CSS to make it look decent. The original idea, that is also the reason why the theme is called "no style, please!", was to create a theme that looked like a plain text document. However, using no CSS at all would have made it hard to read, so I added the least amount of CSS possible to improve readibility, while trying to keep it look like plain text.

**Comment by victorbnl** [comment]
Oh ok so it's not for the CSS itself but for the design. Thanks!
