### ISSUE TITLE
How to make a index.markdown without a menu

### ISSUE THREAD

**Issue by lipangit** [riggraz/no-style-please#4]
Hello :

I am intresting in the style. but the  index page  is a menu I do not need the menu , the index is a content. 

How to show the [page](https://jzvd.github.io/JZVideo/) with no-style-pleae.

Thx

**Comment by riggraz** [comment]
Hello,

you can change the `home.html` layout, adding the following line at the end of the file:

```{{ content }}```

Then you can edit your `index.md` file (that should have layout `home`) and write anything you want. These contents will be displayed in the index page after the menu. If you want to delete the menu, just delete everything in `_data/menu.yml`.

The next version of no-style-please will implement this feature, so users will only have to add content to `index.md` and it will be automatically displayed.
