### ISSUE TITLE
minimum jekyll version? is jekyll 4 supported?

### ISSUE THREAD

**Issue by Pablohn26** [riggraz/no-style-please#5]
Hi,

I am trying to run this theme but I am having some issues with versions and dependencies.

When I try with jekyll 4 I get the following error:

```
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (= 4.1.0)

    no-style-please (= 0.3.1) was resolved to 0.3.1, which depends on
      jekyll (~> 3.8.7)

```

**Comment by hieu6** [comment]
i have the same issue. :( @riggraz halp

**Comment by riggraz** [comment]
Hi,

right now the theme doesn't support Jekyll 4. It works with Jekyll 3.8.7 which is the version of Jekyll that used to run on GitHub pages (now github runs 3.9.0).

I don't want to lose compatibility with github pages, so I don't think I'll update to version 4 soon.
