### ISSUE TITLE
Lazy-loading images

### ISSUE THREAD

**Issue by dmmax** [riggraz/no-style-please#7]
Hey riggraz,

is it possible to implement lazy-loading images into your project? If you don't have enough time for that, please let me know, I will try to do it by mybself

**Comment by riggraz** [comment]
Hi dmmax,

I think that lazy loading is a feature few bloggers really care about, so I don't want to ship the theme with it.

Thanks anyway for the interest in the theme! And good luck with your lazy loading implementation!
