### ISSUE TITLE
Emojis are displayed in the middle of the screen

### ISSUE THREAD

**Issue by PietroArsi** [riggraz/no-style-please#76]
How do I fix this? I want the emojis to be displayed like normal text.

![hK9yQP26CD](https://github.com/riggraz/no-style-please/assets/45829504/17d95308-e56e-40fc-9b5f-5b863d218452)

**Comment by PietroArsi** [comment]
I solved it by pasting the emojis directly in the md file but now all the emojis are rendered with negative colors, is there a way to fix this?

**Comment by tanvincible** [comment]
Closing this as `fixed`.
