### ISSUE TITLE
Hey :)

### ISSUE THREAD

**Issue by ryku-1** [riggraz/no-style-please#8]
Using dark theme on my blog, if I view on mobile, some of my code blocks, pictures escape the dark theme, and propagate half my page white, I have tried changing the body to black in the sass file but unsure what the issue is really....Thanks for you time. https://ryku-1.github.io 

(cheers for the theme btw it is awesome)

**Comment by riggraz** [comment]
Sorry for the late response. I checked your blog and the problem seem solved, isn't it?

**Comment by ryku-1** [comment]
Hey!! No problem, Yeah it has seemed to resolve itself, thank you!

**Comment by riggraz** [comment]
I'm glad to hear that 😄

I'm closing the issue now. See you!
