### ISSUE TITLE
RSS links generates incorrectly

### ISSUE THREAD

**Issue by AXCWG** [riggraz/no-style-please#89]
it generates: 

```
xml:base="//hottake/2024/07/30/Friend_Partner/"
```

instead of 

```
 xml:base="https://<website>/hottake/2024/07/30/Friend_Partner/"
```

could be user error?

**Comment by AXCWG** [comment]
incase: [blog](axcwg.github.io)

**Comment by BrianInGermany** [comment]
Do you have the base url in the config file?

**Comment by AXCWG** [comment]
> Do you have the base url in the config file?

I figured it out a long while ago without closing this issue, sorry.
