### ISSUE TITLE
Minor change to make it really "no-style-please"

### ISSUE THREAD

**Issue by foxviet** [riggraz/no-style-please#9]
I will remove underline for links on the site 😀

**Comment by riggraz** [comment]
Hi foxviet!

Thanks for taking the time to contribute to the theme, I really appreciate it. However, I personally like underlined links, so I'll stick with it for now. Moreover, you actually added 1 more line of CSS to achieve non-underlined links 😜

I'm closing this issue as well as the [related PR](https://github.com/riggraz/no-style-please/pull/10). Thanks again for your time and hopefully I'll see you again around here!
